### ISSUE TITLE
Impossible to includ sodium.h

### ISSUE THREAD

**Issue by ghost** [screeck/YouTube#1]
Idk if im shit as visual studio projects or not but i just tried including sodium.h as no operating system my default ahs that and it completely flops, also theres no sqlite3.h header which is clearly required.

**Comment by BernKing** [comment]
I keep coming across you lmao.
You probably need to have sodium installed in your system. Usually I use vcpkg which is a c/c++ package  manager by Microsoft.

**Comment by ghost** [comment]
sorry i didn't close this issue i just had issues installing packages one time and went f*** it, turns out its much easier using g++ on linux as opposed to visual studio with everything to going over your head
